# Generated by Django 4.0.4 on 2022-05-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='adress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(),
        ),
    ]
