# Generated by Django 4.0.4 on 2022-05-12 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_adress_myuser_gender_alter_myuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
    ]
