# Generated by Django 4.0.4 on 2022-07-19 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 7, 19)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Shopuser'), ('3', 'Customer')], max_length=10),
        ),
    ]
