# Generated by Django 4.0.4 on 2022-07-20 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_dob_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 7, 20)),
        ),
    ]
