# Generated by Django 4.0.4 on 2022-07-20 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='shop_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 20)),
        ),
    ]
