# Generated by Django 4.0.4 on 2022-08-10 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_myuser_adress_alter_myuser_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
