# Generated by Django 4.0.4 on 2022-07-27 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_brand_color_productattribute_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.RenameModel(
            old_name='Size',
            new_name='Material',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '2. Brands'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '3. Colors'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': '4. Materials'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. ProductAttributes'},
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='size',
            new_name='material',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('detail', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('shopuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Products',
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
