# Generated by Django 4.0.4 on 2022-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
